### ISSUE TITLE
"Implement custom filter logic" demo is buggy

### ISSUE THREAD

**Issue by nickhellings** [react-bootstrap-table/react-bootstrap-table2#1007]
It looks like this is related to this issue: https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/682

Basically the demo case found [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Implement%20custom%20filter%20logic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is not correct. 

I created a gif of the problem:
![react bootstrap table 2 issue](https://user-images.githubusercontent.com/7235364/61124565-7a4ef780-a4a7-11e9-8b9d-2a291caea6fe.gif) As you can see the product price filter which overrides the onFilter function has some issues when using multiple columns to filter.

As I read in the other thread apparently I could use [the exposed api](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html#get-current-display-rows) to implement this behavior properly, so at least that hopefully solves my issue, but I thought I should inform you about this bug in the demo.

Good work on the library by the way! I love it.

Have a nice day.

**Comment by AllenFang** [comment]
@nickhellings sorry for lately reply, I will check this out, thanks your finding!!

**Comment by AllenFang** [comment]
I think this is a example bug, I will fix it soon, thank you

**Comment by AllenFang** [comment]
@nickhellings fixed in newest version

**Comment by nickhellings** [comment]
@AllenFang Has this been released? As far as I can see in [custom filter example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Implement%20custom%20filter%20logic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) this is still not working as intended. I think this is not just a bug in the example. It is a bug in the underlying code.

The use case as shown in my GIF in the original post is still not working.

Thanks!

**Comment by AllenFang** [comment]
@nickhellings sorry for my roughy bug checking, there's a bug actually, i will fix it soon,  thanks

**Comment by AllenFang** [comment]
@nickhellings  I fixed in newest version, please upgrade to newest version, thanks
[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/10/version-bump.html) is release note
